"""Vendored LAPACK nobalance eigen (Option B — see ``eig.md`` §25)."""

from python_src.utils.eig_lapack_nobalance.wrapper import (
    dtrevc3_debug_get,
    dtrevc3_debug_get_qr0_sweep_table,
    dtrevc3_debug_get_qr0_sweep37_boundary,
    dtrevc3_debug_get_qr0_sweep7_boundary,
    dtrevc3_debug_get_qr0_sweep6_post_dlaqr5,
    dtrevc3_debug_get_qr0_sweep8_pre_dlaqr5,
    dtrevc3_debug_get_qr5_in_plate,
    dtrevc3_debug_get_qr5_out5_plate,
    dtrevc3_debug_get_qr5_plate_trace,
    dtrevc3_debug_get_qr5_s5_intra_trace,
    dtrevc3_debug_get_qr5_s5_zpre_subtrace,
    dtrevc3_debug_get_qr5_s5_z1_do140,
    dtrevc3_debug_get_qr5_s5_z1_gap,
    dtrevc3_debug_get_qr5_s5_z145_pre_zp1,
    dtrevc3_debug_get_qr5_s5_zp1_boundary,
    dtrevc3_debug_reset,
    dtrevc3_debug_set_col,
    dtrevc3_debug_set_row_pair,
    eig_real_nobalance,
    lapack_nobalance_available,
)

__all__ = [
    "dtrevc3_debug_get",
    "dtrevc3_debug_get_qr0_sweep_table",
    "dtrevc3_debug_get_qr0_sweep37_boundary",
    "dtrevc3_debug_get_qr0_sweep7_boundary",
    "dtrevc3_debug_get_qr0_sweep6_post_dlaqr5",
    "dtrevc3_debug_get_qr0_sweep8_pre_dlaqr5",
    "dtrevc3_debug_get_qr5_in_plate",
    "dtrevc3_debug_get_qr5_out5_plate",
    "dtrevc3_debug_get_qr5_plate_trace",
    "dtrevc3_debug_get_qr5_s5_intra_trace",
    "dtrevc3_debug_get_qr5_s5_zpre_subtrace",
    "dtrevc3_debug_get_qr5_s5_z1_do140",
    "dtrevc3_debug_get_qr5_s5_z1_gap",
    "dtrevc3_debug_get_qr5_s5_z145_pre_zp1",
    "dtrevc3_debug_get_qr5_s5_zp1_boundary",
    "dtrevc3_debug_reset",
    "dtrevc3_debug_set_col",
    "dtrevc3_debug_set_row_pair",
    "eig_real_nobalance",
    "lapack_nobalance_available",
]
